allowBuilds:
  '@firebase/util': false
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: set this to true or false
  prisma: true
  protobufjs: false
  sharp: false
  unrs-resolver: false
  workerd: set this to true or false
